"""
    Frame (CW-B2, ADR 0019 §1)

The per-activation register file plus the metadata needed to return from
a callee to its caller. `IState` (see `src/ir/IState.jl`) holds a
`frames::Vector{Frame}` — a call stack that is never empty — and the
**active** register file is always `frames[end].locals`, reached through
the `active_locals(s)` accessor. Before this chunk the register file was
a single flat `IState.locals` dict; the frame stack lifts that flat dict
to a per-activation stack so that reversible calls (`CallEnter` /
`ReturnExit`, landing in a later CW-B2 chunk) can push and pop activations
without name collisions across recursive invocations (ADR 0019 §5).

# What this is — and what it is NOT yet

This chunk (the FIRST of CW-B2) lands ONLY the `Frame` struct and the
state refactor that wraps the old flat `locals` into a one-element frame
stack. `CallEnter` / `ReturnExit`, `VMProgram.functions`, the `#`-qualified
multi-function ingest, and the End-at-depth>1 routing are deliberately
NOT here (ADR 0019 §3–§4, §8 "Impact (CW-B2)"). For a single-function
program the stack has exactly one frame — `frames[1]`, the `:__entry`
activation wrapping the original `locals` — so this chunk is SUITE-NEUTRAL:
nothing observable changes.

# Field-by-field rationale (ADR 0019 §1)

- `link::Int64`. The caller's return pc in the flat instruction stream
  (`= call_pc + 1`). This is BobISA's saved branch register
  (Thomsen–Axelsen–Glück 2012 §3.2, pp. 5–6 / LNCS 7165 pp. 34–35,
  `references/reversible-isa/axelsen-yokoyama-2011-bobisa.pdf`): the
  return site lives in register state at the target, so the call site is
  recovered FROM STATE on the backward pass rather than from a control
  history tape. For the bottom (`:__entry`) frame there is no caller, so
  `link` is `0` — a sentinel that no live `CallEnter` ever writes (it
  writes `call_pc + 1`, always ≥ 1 in the flat stream).

- `targets::Vector{Symbol}`. The caller's SSA destination names where the
  callee's return values land (the inverse of arg-passing: return landing
  is a MOVE into the caller frame, per Vieri 1995 p. 22,
  `references/reversible-isa/vieri-1995-pendulum-ms.pdf` — "the
  information is merely moved … rather than erased"). Empty (`Symbol[]`)
  for the bottom frame, which returns to nothing.

- `locals::Dict{Symbol,Int64}`. THIS activation's register file, keyed by
  SSA name — the same `Dict{Symbol,Int64}` shape the old flat
  `IState.locals` had, with the same `Int64` value width (ADR 0001
  §Observations; M2.x scalar-width choice). Frame isolation is what makes
  recursion work with no mangling: every activation's `%n` is a key in
  its OWN frame's dict (ADR 0019 §5).

- `fname::Symbol`. The callee name — diagnostics plus `End`-resolution
  checks (ADR 0019 §1, §6). The bottom frame carries `:__entry`, a
  reserved name (the entry activation is not a callee of anything).

# Why immutable, with a mutable Dict field

`Frame` is an **immutable `struct`** (ADR-reviewed). The activation's
identity — its return site, its landing targets, its name — is fixed for
the activation's lifetime; what mutates during the callee's body is the
CONTENTS of its `locals` dict, and a `Dict` field of an immutable struct
is itself still mutable (the binding is frozen, the object it points at
is not). So `step!` mutates `active_locals(s)[dest] = val` in place
exactly as it mutated `s.locals[dest] = val` before — byte-identical for
the bottom frame. Frames are never mutated as units; they are REPLACED by
`push!`/`pop!` on `IState.frames` at call/return boundaries (a later
chunk). This is deliberately the opposite of proposer B's
swap-the-dict-in-IState alternative, which ADR 0019 §1 REJECTS for its
aliasing hazard.

# Why content `==` / `hash` (ADR 0019 §1; ADR 0018 §H / ADR 0008 Finding 3)

`frames` JOINS `IState`'s `Base.:(==)` / `Base.hash`, so `Frame` needs
content equality. Julia's autogenerated `==` for an immutable struct
ALREADY content-compares each field (and `Dict` has a content-comparing
`==`), so the explicit methods below are, field-for-field, what the
compiler would synthesise. We write them out anyway to MATCH THE PROJECT
CONVENTION established for `IState` (`src/ir/IState.jl`): every
round-trip-bearing type spells its `==`/`hash` explicitly so a reader
searching for `==` sees the intent and the rationale, and so the
load-bearing fact — that state which must round-trip is IN the equality
relation — is visible at the definition site, not inferred. ADR 0018 §H /
ADR 0008 Finding 3: state that must round-trip but is absent from `==`
makes round-trip tests pass spuriously (Rule 4).

Ref: docs/adr/0019-reversible-calls.md §1 (frames live in IState; the
     IState.locals field is removed; active register file =
     frames[end].locals via active_locals).
Ref: references/reversible-isa/axelsen-yokoyama-2011-bobisa.pdf §3.2
     (link register = saved branch register; call site recovered from state).
Ref: references/reversible-isa/vieri-1995-pendulum-ms.pdf p. 22
     (argument/return passing is a MOVE, never copy-and-drop).
Ref: references/implementations/RC3/ (RSSAVM.java explicit callStack of
     StackFrames — per-frame locals + return ip + caller direction;
     design lesson only, per CLAUDE.md).
"""
struct Frame
    link::Int64                  # caller's return pc (flat stream; = call_pc + 1)
    targets::Vector{Symbol}      # caller SSA dests where return values land
    locals::Dict{Symbol,Int64}   # this activation's register file
    fname::Symbol                # callee name (diagnostics + End resolution)
    stack_delta::Int64           # CW-C3: the IState.stack_top advance CallEnter
                                 # made entering THIS activation (= the caller's
                                 # frame_size). ReturnExit retracts exactly this
                                 # when popping the frame, so stack_top
                                 # round-trips without needing `prog` at return.

    # 4-arg constructor: stack_delta defaults to 0 (CW-C3). The bottom
    # `:__entry` frame (no CallEnter pushed it — `IState`'s constructors build
    # it) and EVERY hand-built `Frame(link, targets, locals, fname)` test/IState
    # call site keep their meaning: a 0 stack delta means popping the frame
    # retracts `stack_top` by 0 (byte-identical to pre-CW-C3). `CallEnter` uses
    # the 5-arg form with the real caller frame size.
    Frame(link::Int64, targets::Vector{Symbol}, locals::Dict{Symbol,Int64},
          fname::Symbol) = new(link, targets, locals, fname, Int64(0))
    Frame(link::Int64, targets::Vector{Symbol}, locals::Dict{Symbol,Int64},
          fname::Symbol, stack_delta::Integer) =
        new(link, targets, locals, fname, Int64(stack_delta))
end

"""
    Base.:(==)(a::Frame, b::Frame) -> Bool

Content equality on `Frame`: two frames are equal iff their `link`,
`fname`, `targets`, and (the *content of* their) `locals` agree. Spelled
out to match the `IState` convention (`src/ir/IState.jl`); see the
top-of-file rationale "Why content `==` / `hash`". `Vector{Symbol}` and
`Dict{Symbol,Int64}` both carry content-comparing `==` in Base, so each
clause is "use `==`, not `===`".
"""
function Base.:(==)(a::Frame, b::Frame)
    a.link == b.link &&
    a.fname === b.fname &&        # interned Symbol: === and == agree.
    a.stack_delta == b.stack_delta &&  # CW-C3: the stack_top advance must
                                 # round-trip with the frame (Rule 4).
    a.targets == b.targets &&     # Vector's content-comparing ==.
    a.locals == b.locals          # Dict's content-comparing ==.
end

function Base.hash(f::Frame, h::UInt)
    h = hash(f.link, h)
    h = hash(f.fname, h)
    h = hash(f.stack_delta, h)  # CW-C3: hash in lock-step with == above.
    h = hash(f.targets, h)   # Vector's hash respects content + order.
    h = hash(f.locals, h)    # Dict's hash respects content (order-independent).
    return h
end

# NOTE: the `active_locals(s::IState)` accessor (ADR 0019 §1) is defined in
# `src/ir/IState.jl`, immediately after the `IState` struct, because it
# dispatches on `IState` (which is included AFTER this file — `IState`'s
# `frames` field references `Frame`, so `Frame` must be defined first). See
# the BennettVM.jl include-order comment for `call_frames.jl`.

"""
    FunctionEntry (CW-B2, ADR 0019 §2)

The per-function record in `VMProgram.functions` — a function table laid
over the SINGLE flat `blocks` vector. BennettVM keeps one global flat
instruction stream and one `LabelTable` (ADR 0019 §2 rejects proposer B's
per-function `(fn, pc)` addressing); `FunctionEntry` is the closed-world
directory that `CallEnter` ingest consults to resolve a callee name to its
entry label, formal parameters, and return values.

# Field-by-field rationale

- `name::Symbol`. The function's identity, used as the `functions` dict key
  and as the `Frame.fname` of an activation of this function.
- `entry_label::Symbol`. The `#`-qualified label of this function's entry
  block (ADR 0019 §2 — `Symbol(string(name), "#", string(raw_label))`).
  `CallEnter.forward` looks this up in the `LabelTable` to set the callee's
  starting pc (`fwd_address + 1`, one past the Begin marker).
- `params::Vector{Symbol}`. The formal parameter SSA names, in positional
  order — the receiving side of the MOVE that `CallEnter` performs from the
  caller's `args` (Vieri 1995 p.22; arity-checked against `args` in
  `CallEnter`'s fail-loud guard, ADR 0019 §6b).
- `returns::Vector{Symbol}`. The SSA names the function returns, in
  positional order — the sending side of the MOVE that `ReturnExit`
  performs into the caller's `targets` (arity-checked against `targets`,
  ADR 0019 §6c). **CAVEAT (CW-B2b hostile review, risk 1): when populated
  by `_declared_returns` (ingest_multi.jl) this holds the FIRST `IRRet`'s
  SSA name only — for a multi-exit-block function it is NOT authoritative
  for which name flows out at runtime (that is `EndInstruction.returns`).
  Current code uses this field exclusively for `isempty` void detection;
  do not build arity/liveness logic on it without fixing the population
  (bead filed).**
- `frame_size::Int64` (CW-C3, bead `bennettvm-416r.10`). The total number of
  STATIC stack-alloca cells this function reserves — the size of its
  activation record in the global stack segment. `CallEnter` advances
  `IState.stack_top` by the CALLER's `frame_size` (so the callee's allocas
  land past it), `ReturnExit` retracts the same; this is what makes a
  multi-function C `-O0` module's memory-backed locals frame-disjoint (see
  `src/ir/IState.jl` `stack_top`). Defaults to 0 (a function with no static
  allocas / the CW-B frame-register test builders), populated by
  `ingest_multi.jl` from the function's static `IRAlloca` cells.

Ref: docs/adr/0019-reversible-calls.md §2 (function table over one flat
     stream; `#`-qualified labels; closed-world callee resolution at ingest).
"""
struct FunctionEntry
    name::Symbol
    entry_label::Symbol
    params::Vector{Symbol}
    returns::Vector{Symbol}
    frame_size::Int64    # total STATIC stack-alloca cells of this function (CW-C3)

    # `frame_size` defaults to 0 (CW-C3): a function with no static allocas
    # occupies no stack region, and EVERY existing 4-arg `FunctionEntry(name,
    # entry_label, params, returns)` call site (the CW-B `_two_level_module` /
    # factorial test builders, which use frame-register locals, not allocas)
    # keeps its meaning — a zero stack frame means `CallEnter` advances
    # `stack_top` by 0 across it, i.e. no change (byte-identical to pre-CW-C3).
    # The multi-function lowering (`ingest_multi.jl`) populates the real size
    # from the function's static `IRAlloca` cells so a caller of an
    # alloca-bearing callee offsets correctly.
    FunctionEntry(name::Symbol, entry_label::Symbol, params::Vector{Symbol},
                  returns::Vector{Symbol}) =
        new(name, entry_label, params, returns, Int64(0))
    FunctionEntry(name::Symbol, entry_label::Symbol, params::Vector{Symbol},
                  returns::Vector{Symbol}, frame_size::Integer) =
        new(name, entry_label, params, returns, Int64(frame_size))
end

function Base.:(==)(a::FunctionEntry, b::FunctionEntry)
    a.name === b.name &&
    a.entry_label === b.entry_label &&
    a.params == b.params &&
    a.returns == b.returns &&
    a.frame_size == b.frame_size
end

function Base.hash(f::FunctionEntry, h::UInt)
    h = hash(f.name, h)
    h = hash(f.entry_label, h)
    h = hash(f.params, h)
    h = hash(f.returns, h)
    h = hash(f.frame_size, h)
    return h
end
